import { atom } from "recoil";
const dataState = atom({
  key: "dataState",
  default: [
    {
      id: "754592747888971776",
      ruleId: "5",
      ruleName: "油位比例异常", //告警名称
      deletedFlag: null,
      createTime: "2022-08-10 04:03:16",
      updateTime: null,
      stationId: "bdz001",
      stationName:
        "智慧A变电站彩虹信息有限公司彩虹信息有限公司彩虹信息有限公司",
      equipNameEn: "yz001",
      equipNameCh: "1号变压器油枕",
      equipType: "bj",
      alertStatus: 2,
      collectedTime: "1660075341062",
      collectedEndTime: null,
      continuedTime: 5.86,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds219","nameCh":"实时油位比例","value":"50.0","unit":"%"}]',
      originalCriterionPointList: '[{"name":"sds.sds219","value":"50.0"}]',
      remark: "遥控器场景：\n油位比例(80,100)异常；(20,80]正常",
      dataCriterionNameEn: "sds",
      equipId: "1463000355058388994",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 3,
      alertCount: 2861,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: false,
    },
    {
      id: "754592747700228096",
      ruleId: "5",
      ruleName: "油位比例异常",
      deletedFlag: null,
      createTime: "2022-08-10 04:03:16",
      updateTime: null,
      stationId: "bdz001",
      stationName:
        "智慧A变电站彩虹信息有限公司彩虹信息有限公司彩虹信息有限公司",
      equipNameEn: "YZ",
      equipNameCh: "主变油枕",
      equipType: "bj",
      alertStatus: 2,
      collectedTime: "1660075341062",
      collectedEndTime: null,
      continuedTime: 5.86,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds219","nameCh":"实时油位比例","value":"50.0","unit":"%"}]',
      originalCriterionPointList: '[{"name":"sds.sds219","value":"50.0"}]',
      remark: "遥控器场景：\n油位比例(80,100)异常；(20,80]正常",
      dataCriterionNameEn: "sds",
      equipId: "1463081515692216321",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 3,
      alertCount: 2875,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: false,
    },
    {
      id: "754592747268214785",
      ruleId: "5",
      ruleName: "油位比例异常",
      deletedFlag: null,
      createTime: "2022-08-10 04:03:16",
      updateTime: null,
      stationId: "bdz001",
      stationName:
        "智慧A变电站彩虹信息有限公司彩虹信息有限公司彩虹信息有限公司",
      equipNameEn: "bdz001xq1",
      equipNameCh: "智慧A一间隔",
      equipType: "zbjg",
      alertStatus: 2,
      collectedTime: "1660075341062",
      collectedEndTime: null,
      continuedTime: 5.86,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds219","nameCh":"实时油位比例","value":"50.0","unit":"%"}]',
      originalCriterionPointList: '[{"name":"sds.sds219","value":"50.0"}]',
      remark: "遥控器场景：\n油位比例(80,100)异常；(20,80]正常",
      dataCriterionNameEn: "sds",
      equipId: "1",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 3,
      alertCount: 83,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: false,
    },
    {
      id: "754592747268214784",
      ruleId: "5",
      ruleName: "油位比例异常",
      deletedFlag: null,
      createTime: "2022-08-10 04:03:16",
      updateTime: null,
      stationId: "bdz001",
      stationName:
        "智慧A变电站彩虹信息有限公司彩虹信息有限公司彩虹信息有限公司",
      equipNameEn: "1ZB",
      equipNameCh: "一号主变",
      equipType: "abbyq",
      alertStatus: 1,
      collectedTime: "1660075341062",
      collectedEndTime: null,
      continuedTime: 5.86,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds219","nameCh":"实时油位比例","value":"50.0","unit":"%"}]',
      originalCriterionPointList: '[{"name":"sds.sds219","value":"50.0"}]',
      remark: "遥控器场景：\n油位比例(80,100)异常；(20,80]正常",
      dataCriterionNameEn: "sds",
      equipId: "84705685337673750",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 3,
      alertCount: 3610,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: true,
    },
    {
      id: "749688713629536256",
      ruleId: "115549073485991936",
      ruleName: "本体温度异常",
      deletedFlag: null,
      createTime: "2022-07-27 15:16:24",
      updateTime: null,
      stationId: "bdz110",
      stationName: "cj电站",
      equipNameEn: "zb99",
      equipNameCh: "99号变压器",
      equipType: "abbyq",
      alertStatus: 3,
      collectedTime: "1658906183359",
      collectedEndTime: null,
      continuedTime: 330.63,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds202","nameCh":"本体温度","value":"80.120000","unit":"℃"}]',
      originalCriterionPointList: '[{"name":"sds.sds202","value":"80.120000"}]',
      remark: "阈值规则：热点温度＞80℃为关注状态，否则为正常状态",
      dataCriterionNameEn: "sds",
      equipId: "280381445749477376",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 3,
      alertCount: 2,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: false,
    },
    {
      id: "748892622935953408",
      ruleId: "255058812782907392",
      ruleName: "油温异常",
      deletedFlag: null,
      createTime: "2022-07-25 10:33:01",
      updateTime: null,
      stationId: "bdz001",
      stationName: "智慧A变电站",
      equipNameEn: "1ZB",
      equipNameCh: "一号主变",
      equipType: "abbyq",
      alertStatus: 3,
      collectedTime: "1658745430000",
      collectedEndTime: null,
      continuedTime: -1,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds220","nameCh":"实时油温","value":"100.74750828621825","unit":"℃"}]',
      originalCriterionPointList:
        '[{"name":"sds.sds220","value":"100.74750828621825"}]',
      remark:
        "阈值规则：\n实时油温 在>105℃：严重；>95℃：一般；>80℃：关注\n其余：正常",
      dataCriterionNameEn: "sds",
      equipId: "84705685337673750",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 1,
      alertCount: 8,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: true,
    },
    {
      id: "747232326660001792",
      ruleId: "255058812782907392",
      ruleName: "油温异常",
      deletedFlag: null,
      createTime: "2022-07-20 20:35:35",
      updateTime: null,
      stationId: "bdz001",
      stationName: "智慧A变电站",
      equipNameEn: "YZ",
      equipNameCh: "主变油枕",
      equipType: "bj",
      alertStatus: 2,
      collectedTime: "1658320533431",
      collectedEndTime: null,
      continuedTime: 493.31,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds220","nameCh":"实时油温","value":"85.100000","unit":"℃"}]',
      originalCriterionPointList: '[{"name":"sds.sds220","value":"85.100000"}]',
      remark:
        "阈值规则：\n实时油温 在>105℃：严重；>95℃：一般；>80℃：关注\n其余：正常",
      dataCriterionNameEn: "sds",
      equipId: "1463081515692216321",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 3,
      alertCount: 1,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: false,
    },
    {
      id: "747232325573677056",
      ruleId: "255058812782907392",
      ruleName: "油温异常",
      deletedFlag: null,
      createTime: "2022-07-20 20:35:35",
      updateTime: null,
      stationId: "bdz001",
      stationName: "智慧A变电站",
      equipNameEn: "1ZB",
      equipNameCh: "一号主变",
      equipType: "abbyq",
      alertStatus: 2,
      collectedTime: "1658320533431",
      collectedEndTime: null,
      continuedTime: 493.31,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds220","nameCh":"实时油温","value":"85.100000","unit":"℃"}]',
      originalCriterionPointList: '[{"name":"sds.sds220","value":"85.100000"}]',
      remark:
        "阈值规则：\n实时油温 在>105℃：严重；>95℃：一般；>80℃：关注\n其余：正常",
      dataCriterionNameEn: "sds",
      equipId: "84705685337673750",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 3,
      alertCount: 1,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: true,
    },
    {
      id: "747234697175764992",
      ruleId: "5",
      ruleName: "油位比例异常",
      deletedFlag: null,
      createTime: "2022-07-20 20:45:01",
      updateTime: null,
      stationId: "bdz001",
      stationName: "智慧A变电站",
      equipNameEn: "2ZB",
      equipNameCh: "二号主变",
      equipType: "abbyq",
      alertStatus: 4,
      collectedTime: "1658316470712",
      collectedEndTime: null,
      continuedTime: 494.44,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds219","nameCh":"实时油位比例","value":"59.1","unit":"%"}]',
      originalCriterionPointList: '[{"name":"sds.sds219","value":"59.1"}]',
      remark: "遥控器场景：\n油位比例(80,100)异常；(20,80]正常",
      dataCriterionNameEn: "sds",
      equipId: "84705685341868054",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 3,
      alertCount: 3413,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: true,
    },
    {
      id: "747234696232046592",
      ruleId: "5",
      ruleName: "油位比例异常",
      deletedFlag: null,
      createTime: "2022-07-20 20:45:00",
      updateTime: null,
      stationId: "bdz001",
      stationName: "智慧A变电站",
      equipNameEn: "1YZ",
      equipNameCh: "主变油枕",
      equipType: "bj",
      alertStatus: 2,
      collectedTime: "1658316470712",
      collectedEndTime: null,
      continuedTime: 494.44,
      relieveFlag: 1,
      criterionPointList:
        '[{"name":"sds.sds219","nameCh":"实时油位比例","value":"59.1","unit":"%"}]',
      originalCriterionPointList: '[{"name":"sds.sds219","value":"59.1"}]',
      remark: "遥控器场景：\n油位比例(80,100)异常；(20,80]正常",
      dataCriterionNameEn: "sds",
      equipId: "1549592236944052226",
      taskId: null,
      subEquipId: null,
      subEquipNameCh: null,
      pointName: null,
      pointType: null,
      alertType: 3,
      alertCount: 1,
      criterionPointNameEn: null,
      criterionPointValue: null,
      startTime: null,
      endTime: null,
      mainEquip: false,
    },
  ],
});
export { dataState };
